// %10,2 means 8, 9, 10, 11, or 12
var activities = [
	"Do %15,5 jumping jacks.",
	"Do %11,5 pushups.",
	"Do %20,10 seconds of plank.",
	"Run in place for %25,8 seconds.",
	"Do %15,5 high knees for each leg.",
	"Take a stretch.",
	"Do %9,3 wall pushups.",
	"Spin in a circle %3,1 times to the left, then %3,1 times to the right.",
	"Make %10,3 small circles with your arms.",
	"Jump over a pencil %8,3 times.",
	"Jump as high as you can %8,3 times.",
	"Do %10,4 situps",
	"Do %10,4 crunches",
	"Take a fighting stance, jab %10,5 times, and cross %10,5 times.",
	"Climb %9,3 rungs of an invisible ladder.",
	"Wall sit for %15,5 seconds.",
	"Hop from your left foot to your right foot %15,4 times.",
	"Pedal your legs for %14,2 seconds.",
	"Do %13,3 squats.",
	"Do %11,5 tricep dips.",
	"Walk around the room %2,1 times.",
	"Run around the room %2,1 times.",
	"Do %11,3 step-ups onto a chair.",
	"Do %10,3 lunges.",
	"Do %6,2 pushups with rotation.",
	"Do %15,3 seconds of side plank",
	"Stand up and touch your toes %8,3",
	"Lay down and do %10,2 bicycle crunches.",
	""
]
